# Generated by Django 5.2.14 on 2026-05-27 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amfi_code', models.CharField(db_index=True, help_text="AMFI scheme code (e.g. '120503')", max_length=10, unique=True)),
                ('isin_growth', models.CharField(blank=True, db_index=True, help_text='ISIN for Growth plan', max_length=15, null=True)),
                ('isin_idcw', models.CharField(blank=True, help_text='ISIN for IDCW plan', max_length=15, null=True)),
                ('scheme_name', models.CharField(max_length=300)),
                ('fund_house', models.CharField(db_index=True, max_length=200)),
                ('scheme_type', models.CharField(help_text="'Open Ended' / 'Close Ended' / 'Interval'", max_length=100)),
                ('scheme_category', models.CharField(db_index=True, help_text='Full SEBI category string', max_length=200)),
                ('plan', models.CharField(choices=[('GROWTH', 'Growth'), ('IDCW', 'IDCW')], db_index=True, default='GROWTH', max_length=10)),
                ('is_direct', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('morningstar_id', models.CharField(blank=True, help_text="Morningstar SecId e.g. 'F00000PDX2'", max_length=20, null=True)),
                ('yahoo_ticker', models.CharField(blank=True, help_text="Yahoo Finance ticker e.g. '0P000PDX2.BO'", max_length=30, null=True)),
                ('kuvera_code', models.CharField(blank=True, help_text="Kuvera/captnemo 'code' field", max_length=30, null=True)),
                ('expense_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('aum_cr', models.DecimalField(blank=True, decimal_places=2, help_text='AUM in crores', max_digits=12, null=True)),
                ('nav_latest', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('nav_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['scheme_name'],
                'indexes': [models.Index(fields=['scheme_category', 'is_direct', 'plan'], name='funds_schem_scheme__392f58_idx'), models.Index(fields=['fund_house', 'is_active'], name='funds_schem_fund_ho_aed7b9_idx'), models.Index(fields=['is_direct', 'plan', 'is_active'], name='funds_schem_is_dire_9796b4_idx')],
            },
        ),
        migrations.CreateModel(
            name='SchemeMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lump_available', models.BooleanField(default=True)),
                ('lump_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lump_min_additional', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sip_available', models.BooleanField(default=True)),
                ('sip_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sip_dates', models.JSONField(blank=True, default=list, help_text='List of valid SIP date strings')),
                ('sip_multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('redemption_allowed', models.BooleanField(default=True)),
                ('switch_allowed', models.BooleanField(default=True)),
                ('stp_flag', models.BooleanField(default=False)),
                ('swp_flag', models.BooleanField(default=False)),
                ('lock_in_period', models.IntegerField(default=0, help_text='Lock-in period in days')),
                ('tax_period', models.IntegerField(default=0, help_text='Tax lock-in period in days')),
                ('expense_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('expense_ratio_date', models.DateField(blank=True, null=True)),
                ('aum', models.BigIntegerField(blank=True, help_text='AUM in crores', null=True)),
                ('fund_rating', models.IntegerField(blank=True, help_text='Kuvera rating 1-5', null=True)),
                ('fund_rating_date', models.DateField(blank=True, null=True)),
                ('volatility', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('returns_1w', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('returns_1m', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('returns_3m', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('returns_1y', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('returns_3y', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('returns_5y', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('returns_inception', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('fund_manager', models.TextField(blank=True, help_text='Semicolon-separated manager names')),
                ('crisil_rating', models.CharField(blank=True, max_length=100)),
                ('investment_objective', models.TextField(blank=True)),
                ('portfolio_turnover', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('start_date', models.DateField(blank=True, help_text='Fund inception date', null=True)),
                ('detail_info_url', models.URLField(blank=True, help_text='Link to SID/KIM document')),
                ('ms_rating', models.IntegerField(blank=True, help_text='Morningstar star rating 1-5', null=True)),
                ('ms_category', models.CharField(blank=True, max_length=150)),
                ('ms_category_rank', models.IntegerField(blank=True, null=True)),
                ('comparison_peers', models.JSONField(blank=True, default=list, help_text='Raw comparison list from captnemo')),
                ('last_fetched', models.DateTimeField(auto_now=True)),
                ('fetch_source', models.CharField(default='captnemo', max_length=50)),
                ('scheme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='funds.scheme')),
            ],
            options={
                'verbose_name': 'Scheme Metadata',
                'verbose_name_plural': 'Scheme Metadata',
            },
        ),
        migrations.CreateModel(
            name='NAVHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('nav', models.DecimalField(decimal_places=4, max_digits=12)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_history', to='funds.scheme')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['scheme', 'date'], name='funds_navhi_scheme__315ce6_idx'), models.Index(fields=['date'], name='funds_navhi_date_c8907c_idx')],
                'unique_together': {('scheme', 'date')},
            },
        ),
    ]
