# Generated by Django 5.2.14 on 2026-06-15 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundScreenerSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund_name', models.CharField(max_length=300)),
                ('fund_house', models.CharField(db_index=True, max_length=200)),
                ('category_group', models.CharField(db_index=True, max_length=40)),
                ('scheme_sub_category', models.CharField(blank=True, db_index=True, max_length=120)),
                ('income_type', models.CharField(blank=True, db_index=True, max_length=30)),
                ('plan_type', models.CharField(blank=True, db_index=True, max_length=30)),
                ('is_direct', models.BooleanField(db_index=True, default=False)),
                ('is_etf', models.BooleanField(db_index=True, default=False)),
                ('benchmark_type', models.CharField(blank=True, db_index=True, max_length=40)),
                ('benchmark_name', models.CharField(blank=True, db_index=True, max_length=160)),
                ('risk_label', models.CharField(blank=True, db_index=True, max_length=30)),
                ('aum_cr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expense_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fund_age_years', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('returns_1y_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('returns_3y_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('returns_5y_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('cagr_3y_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('rolling_return_3y_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('volatility_3y_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('data_as_of', models.DateField(blank=True, db_index=True, null=True)),
                ('nav_as_of', models.DateField(blank=True, null=True)),
                ('analytics_as_of', models.DateField(blank=True, null=True)),
                ('metadata_as_of', models.DateTimeField(blank=True, null=True)),
                ('source_notes', models.CharField(blank=True, max_length=200)),
                ('scheme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screener_snapshot', to='funds.scheme')),
            ],
            options={
                'ordering': ['fund_name'],
                'indexes': [models.Index(fields=['category_group', 'scheme_sub_category'], name='funds_funds_categor_bdc69e_idx'), models.Index(fields=['fund_house', 'category_group'], name='funds_funds_fund_ho_1e005f_idx'), models.Index(fields=['plan_type', 'is_direct'], name='funds_funds_plan_ty_f3c03d_idx'), models.Index(fields=['benchmark_type', 'benchmark_name'], name='funds_funds_benchma_3e32cf_idx'), models.Index(fields=['cagr_3y_pct'], name='funds_funds_cagr_3y_eb9ff4_idx'), models.Index(fields=['rolling_return_3y_pct'], name='funds_funds_rolling_da7f4d_idx'), models.Index(fields=['volatility_3y_pct'], name='funds_funds_volatil_f34fb5_idx'), models.Index(fields=['data_as_of'], name='funds_funds_data_as_7dee7b_idx')],
            },
        ),
    ]
