# Generated by Django 5.2.14 on 2026-06-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_fundscreenersnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='excess_return_1y',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='1Y fund CAGR minus benchmark CAGR', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='excess_return_3y',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='3Y fund CAGR minus benchmark CAGR', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='max_drawdown',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='3Y max drawdown %', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='rolling_return_5y_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='sharpe_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='3Y Sharpe ratio', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='sortino_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='3Y Sortino ratio', max_digits=8, null=True),
        ),
        migrations.AddIndex(
            model_name='fundscreenersnapshot',
            index=models.Index(fields=['sharpe_ratio'], name='funds_funds_sharpe__69f4df_idx'),
        ),
        migrations.AddIndex(
            model_name='fundscreenersnapshot',
            index=models.Index(fields=['excess_return_1y'], name='funds_funds_excess__e275e4_idx'),
        ),
        migrations.AddIndex(
            model_name='fundscreenersnapshot',
            index=models.Index(fields=['excess_return_3y'], name='funds_funds_excess__b60523_idx'),
        ),
    ]
