# Generated by Django 5.2.14 on 2026-06-25 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0003_screener_enhanced_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_group', models.CharField(db_index=True, max_length=40)),
                ('scheme_sub_category', models.CharField(db_index=True, max_length=120, unique=True)),
                ('benchmark_name', models.CharField(blank=True, max_length=160)),
                ('fund_count', models.IntegerField(default=0)),
                ('avg_return_1y', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('max_return_1y', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('min_return_1y', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('median_return_1y', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('avg_return_3y', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('max_return_3y', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('min_return_3y', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('median_return_3y', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('avg_return_5y', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('max_return_5y', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('min_return_5y', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('median_return_5y', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('avg_volatility', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('avg_sharpe', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('avg_sortino', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('avg_max_drawdown', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('avg_model_score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('pct_strong', models.DecimalField(blank=True, decimal_places=1, help_text='% funds with score >= 75', max_digits=5, null=True)),
                ('pct_good', models.DecimalField(blank=True, decimal_places=1, help_text='% funds with score 55–75', max_digits=5, null=True)),
                ('pct_fair', models.DecimalField(blank=True, decimal_places=1, help_text='% funds with score 40–55', max_digits=5, null=True)),
                ('pct_weak', models.DecimalField(blank=True, decimal_places=1, help_text='% funds with score < 40', max_digits=5, null=True)),
                ('data_as_of', models.DateField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'Category Snapshot',
                'verbose_name_plural': 'Category Snapshots',
                'ordering': ['category_group', 'scheme_sub_category'],
            },
        ),
        migrations.CreateModel(
            name='FundModelScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score_version', models.CharField(default='1.0', help_text='scorer.MODEL_VERSION at compute time', max_length=10)),
                ('final_score', models.DecimalField(blank=True, decimal_places=1, help_text='Overall composite score 0–100', max_digits=5, null=True)),
                ('confidence', models.CharField(blank=True, help_text='RATED / PROVISIONAL / UNRATED', max_length=20)),
                ('score_badge', models.CharField(blank=True, help_text='Strong / Good / Fair / Weak / Poor', max_length=20)),
                ('score_performance', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('score_risk', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('score_cost', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('score_composition', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('perf_status', models.CharField(blank=True, max_length=20)),
                ('risk_status', models.CharField(blank=True, max_length=20)),
                ('cost_status', models.CharField(blank=True, max_length=20)),
                ('comp_status', models.CharField(blank=True, max_length=20)),
                ('red_flags_json', models.JSONField(blank=True, default=list, help_text='List of red flag dicts from scorer')),
                ('red_flag_penalty', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('overall_interpretation', models.TextField(blank=True)),
                ('nav_days', models.IntegerField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fund Model Score',
            },
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='quartile_model_score',
            field=models.IntegerField(blank=True, db_index=True, help_text='Q1–Q4 rank for model score (higher = Q1)', null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='quartile_return_1y',
            field=models.IntegerField(blank=True, db_index=True, help_text='Q1–Q4 rank for 1Y return within sub-category', null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='quartile_return_3y',
            field=models.IntegerField(blank=True, db_index=True, help_text='Q1–Q4 rank for 3Y return within sub-category', null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='quartile_return_5y',
            field=models.IntegerField(blank=True, db_index=True, help_text='Q1–Q4 rank for 5Y return within sub-category', null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='quartile_sharpe',
            field=models.IntegerField(blank=True, help_text='Q1–Q4 rank for Sharpe ratio (higher = Q1)', null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='quartile_sortino',
            field=models.IntegerField(blank=True, help_text='Q1–Q4 rank for Sortino ratio (higher = Q1)', null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='quartile_volatility',
            field=models.IntegerField(blank=True, help_text='Q1–Q4 rank for volatility (lower vol = Q1)', null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='rank_count_in_cat',
            field=models.IntegerField(blank=True, help_text='Total peers in this sub-category at rank time', null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='rank_return_1y',
            field=models.IntegerField(blank=True, help_text='Numeric rank within sub-category for 1Y return', null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='rank_return_3y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='rank_return_5y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='returns_1m_pct',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='1-month return %', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='returns_1w_pct',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='1-week return %', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='returns_3m_pct',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='3-month return %', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='returns_6m_pct',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='6-month return %', max_digits=8, null=True),
        ),
        migrations.AddIndex(
            model_name='fundscreenersnapshot',
            index=models.Index(fields=['quartile_return_1y'], name='funds_funds_quartil_929dca_idx'),
        ),
        migrations.AddIndex(
            model_name='fundscreenersnapshot',
            index=models.Index(fields=['quartile_return_3y'], name='funds_funds_quartil_0ebadc_idx'),
        ),
        migrations.AddIndex(
            model_name='fundscreenersnapshot',
            index=models.Index(fields=['quartile_return_5y'], name='funds_funds_quartil_cd3b8f_idx'),
        ),
        migrations.AddIndex(
            model_name='fundscreenersnapshot',
            index=models.Index(fields=['quartile_model_score'], name='funds_funds_quartil_8ab362_idx'),
        ),
        migrations.AddIndex(
            model_name='categorysnapshot',
            index=models.Index(fields=['category_group'], name='funds_categ_categor_ef78f5_idx'),
        ),
        migrations.AddIndex(
            model_name='categorysnapshot',
            index=models.Index(fields=['data_as_of'], name='funds_categ_data_as_df4686_idx'),
        ),
        migrations.AddField(
            model_name='fundmodelscore',
            name='scheme',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='model_score', to='funds.scheme'),
        ),
        migrations.AddIndex(
            model_name='fundmodelscore',
            index=models.Index(fields=['final_score'], name='funds_fundm_final_s_cd9cfb_idx'),
        ),
        migrations.AddIndex(
            model_name='fundmodelscore',
            index=models.Index(fields=['confidence'], name='funds_fundm_confide_576222_idx'),
        ),
    ]
