# Generated by Django 5.2.14 on 2026-06-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0004_home_dashboard_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorysnapshot',
            name='calendar_returns_json',
            field=models.JSONField(blank=True, default=dict, help_text='Avg category CAGR % by calendar year. Format: {"2018": 12.3, "2019": 8.1, ...}'),
        ),
        migrations.AddField(
            model_name='categorysnapshot',
            name='quarterly_returns_json',
            field=models.JSONField(blank=True, default=dict, help_text='Avg category trailing return % for standard periods. Format: {"1W": 0.5, "1M": 1.2, "3M": 4.5, "6M": 8.0, "1Y": 14.2, "3Y": 11.1, "5Y": 13.5}'),
        ),
    ]
