# Generated by Django 5.2.14 on 2026-06-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0005_home_research_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorysnapshot',
            name='excess_return_1y',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='categorysnapshot',
            name='excess_return_3y',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='categorysnapshot',
            name='rolling_returns_json',
            field=models.JSONField(blank=True, default=dict, help_text='Avg category rolling return stats (1Y/3Y/5Y). Format: {"1Y": {"avg": 12.3, "max": 20.1, "min": -5.4, "pos_pct": 80.5}, ...}'),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='rolling_returns_json',
            field=models.JSONField(blank=True, default=dict, help_text='Avg rolling return stats (1Y/3Y/5Y) for the scheme'),
        ),
    ]
