# Generated by Django 5.2.14 on 2026-06-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0006_categorysnapshot_excess_return_1y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='calendar_returns_json',
            field=models.JSONField(blank=True, default=dict, help_text='Calendar year returns for the scheme'),
        ),
    ]
