# Generated by Django 5.2.14 on 2026-06-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0007_fundscreenersnapshot_calendar_returns_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorysnapshot',
            name='avg_max_drawdown_5y',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='categorysnapshot',
            name='avg_sharpe_5y',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='categorysnapshot',
            name='avg_sortino_5y',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='categorysnapshot',
            name='avg_volatility_5y',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='max_drawdown_5y',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='5Y max drawdown %', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='sharpe_ratio_5y',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='5Y Sharpe ratio', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='sortino_ratio_5y',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='5Y Sortino ratio', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='volatility_5y_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
