# Generated by Django 5.2.14 on 2026-06-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0008_categorysnapshot_avg_max_drawdown_5y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundmodelscore',
            name='debt_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='fundmodelscore',
            name='manager_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='fundmodelscore',
            name='score_debt',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='fundmodelscore',
            name='score_manager',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
