# Generated by Django 5.2.14 on 2026-07-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0009_fundmodelscore_debt_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='alpha_3y',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="3Y annualised Jensen's alpha %", max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='alpha_5y',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="5Y annualised Jensen's alpha %", max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='beta_3y',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='3Y Beta vs benchmark', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='beta_5y',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='5Y Beta vs benchmark', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='cagr_10y_pct',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='10Y trailing CAGR %', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='cagr_7y_pct',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='7Y trailing CAGR %', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='cagr_si_pct',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Since-inception CAGR %', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='crisil_rating',
            field=models.CharField(blank=True, help_text='CRISIL fund rating', max_length=100),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='current_drawdown',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Current drawdown from 1Y peak (%)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='downside_capture_3y',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='3Y downside capture ratio %', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='fund_manager',
            field=models.TextField(blank=True, help_text='Semicolon-separated manager names'),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='info_ratio_3y',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='3Y information ratio', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='info_ratio_5y',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='5Y information ratio', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='lock_in_days',
            field=models.IntegerField(blank=True, help_text='Lock-in period in days', null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='lump_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum lumpsum amount', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='model_score',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=1, help_text='Our composite model score 0–100', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='model_score_badge',
            field=models.CharField(blank=True, help_text='Score badge: Strong/Good/Fair/Weak/Poor', max_length=20),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='nav_latest',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Latest NAV value', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='portfolio_turnover',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Portfolio turnover ratio', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='r_squared_3y',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='3Y R-squared vs benchmark (%)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='r_squared_5y',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='5Y R-squared vs benchmark (%)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='romad_3y',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Return over Max Drawdown: 3Y CAGR / |3Y Max DD|', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='sip_available',
            field=models.BooleanField(blank=True, help_text='SIP investment available', null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='sip_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum SIP amount', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='tracking_error_3y',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='3Y annualised tracking error %', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='tracking_error_5y',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='5Y annualised tracking error %', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='upside_capture_3y',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='3Y upside capture ratio %', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='fundmodelscore',
            name='score_version',
            field=models.CharField(default='2.0', help_text='scorer.MODEL_VERSION at compute time', max_length=10),
        ),
        migrations.AddIndex(
            model_name='fundscreenersnapshot',
            index=models.Index(fields=['cagr_7y_pct'], name='funds_funds_cagr_7y_f478b5_idx'),
        ),
        migrations.AddIndex(
            model_name='fundscreenersnapshot',
            index=models.Index(fields=['cagr_10y_pct'], name='funds_funds_cagr_10_63d977_idx'),
        ),
        migrations.AddIndex(
            model_name='fundscreenersnapshot',
            index=models.Index(fields=['model_score'], name='funds_funds_model_s_b99002_idx'),
        ),
        migrations.AddIndex(
            model_name='fundscreenersnapshot',
            index=models.Index(fields=['alpha_3y'], name='funds_funds_alpha_3_ac24a5_idx'),
        ),
        migrations.AddIndex(
            model_name='fundscreenersnapshot',
            index=models.Index(fields=['current_drawdown'], name='funds_funds_current_6340e2_idx'),
        ),
    ]
