# Generated by Django 5.2.14 on 2026-07-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0010_screener_extended_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='alpha_si',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='away_from_ath_pct',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Current drawdown from all-time high (%)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='beta_si',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='category_st_dev',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='downside_capture_si',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='excess_cat_1y',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='excess_cat_3y',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='excess_cat_5y',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='excess_cat_7y',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='info_ratio_si',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='max_drawdown_1y',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='max_drawdown_si',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='port_cash_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='port_debt_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='port_equity_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='port_top10_concentration',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='port_top3_concentration',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='port_top5_concentration',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='r_squared_si',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='romad_si',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='sharpe_ratio_si',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='sortino_ratio_si',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='upside_capture_si',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='volatility_1y_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='volatility_7y_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='volatility_si_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
