# Generated by Django 5.2.14 on 2026-07-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0011_fundscreenersnapshot_alpha_si_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schememeta',
            name='aum',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='AUM in crores', max_digits=14, null=True),
        ),
    ]
