# Generated by Django 5.2.14 on 2026-07-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0012_alter_schememeta_aum'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='rolling_min_3y_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='rolling_min_5y_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='rolling_min_7y_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='rolling_return_7y_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
