# Generated by Django 5.2.14 on 2026-07-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0014_add_rolling_median_and_category_snapshot_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='is_etf',
            field=models.BooleanField(db_index=True, default=False, help_text='True for ETFs (detected from scheme name)'),
        ),
        migrations.AlterField(
            model_name='fundscreenersnapshot',
            name='category_alpha_3y',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Category avg alpha_3y at time of ranking', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='fundscreenersnapshot',
            name='category_beta_3y',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Category avg beta_3y at time of ranking', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='fundscreenersnapshot',
            name='category_expense_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Category avg expense_ratio at time of ranking', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='fundscreenersnapshot',
            name='category_turnover',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Category avg portfolio_turnover at time of ranking', max_digits=8, null=True),
        ),
    ]
