# Generated by Django 5.2.14 on 2026-08-22 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0015_add_scheme_is_etf'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryInflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('as_of_month', models.DateField(help_text='YYYY-MM-01 — first of the month')),
                ('category_group', models.CharField(db_index=True, help_text='AMFI broad category: Equity, Debt, Hybrid, Solution Oriented, Other, ETF', max_length=80)),
                ('gross_purchase', models.DecimalField(blank=True, decimal_places=2, help_text='Gross purchases / subscriptions (₹ Cr)', max_digits=16, null=True)),
                ('gross_redemption', models.DecimalField(blank=True, decimal_places=2, help_text='Gross redemptions (₹ Cr)', max_digits=16, null=True)),
                ('net_inflow', models.DecimalField(blank=True, decimal_places=2, help_text='Net inflow = gross_purchase - gross_redemption (₹ Cr)', max_digits=16, null=True)),
                ('aum_cr', models.DecimalField(blank=True, decimal_places=2, help_text='Industry AUM for this category at month end (₹ Cr)', max_digits=16, null=True)),
                ('folio_count', models.BigIntegerField(blank=True, help_text='Number of folios at month end', null=True)),
            ],
            options={
                'ordering': ['-as_of_month', 'category_group'],
                'indexes': [models.Index(fields=['as_of_month'], name='funds_indus_as_of_m_132bec_idx'), models.Index(fields=['category_group'], name='funds_indus_categor_29c2f7_idx')],
                'unique_together': {('as_of_month', 'category_group')},
            },
        ),
        migrations.CreateModel(
            name='FundScoreTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('as_of_week', models.DateField(help_text='Monday of the ISO week this snapshot was taken')),
                ('final_score', models.DecimalField(blank=True, decimal_places=1, help_text='Composite model score 0–100 at this snapshot', max_digits=5, null=True)),
                ('score_badge', models.CharField(blank=True, help_text='Strong / Good / Fair / Weak / Poor', max_length=20)),
                ('rank_in_cat', models.IntegerField(blank=True, help_text='Numeric rank within sub-category at snapshot time', null=True)),
                ('cat_total', models.IntegerField(blank=True, help_text='Total peers in sub-category at snapshot time', null=True)),
                ('sub_category', models.CharField(blank=True, help_text='Sub-category name at snapshot time (denormalised)', max_length=120)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_trend', to='funds.scheme')),
            ],
            options={
                'ordering': ['-as_of_week'],
                'indexes': [models.Index(fields=['scheme', 'as_of_week'], name='funds_funds_scheme__a49a93_idx')],
                'unique_together': {('scheme', 'as_of_week')},
            },
        ),
        migrations.CreateModel(
            name='SchemeAumSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('as_of_month', models.DateField(help_text='YYYY-MM-01 — first of the month')),
                ('aum_cr', models.DecimalField(blank=True, decimal_places=2, help_text='AUM in crores at end of this month', max_digits=14, null=True)),
                ('source', models.CharField(default='captnemo', max_length=20)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aum_snapshots', to='funds.scheme')),
            ],
            options={
                'ordering': ['-as_of_month'],
                'indexes': [models.Index(fields=['scheme', 'as_of_month'], name='funds_schem_scheme__cfd9d9_idx'), models.Index(fields=['as_of_month'], name='funds_schem_as_of_m_e2cff0_idx')],
                'unique_together': {('scheme', 'as_of_month')},
            },
        ),
    ]
