# Generated by Django 5.2.14 on 2026-08-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0016_aum_snapshot_score_trend_industry_inflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='aum_1m_change_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='AUM change % vs 1 month ago (from SchemeAumSnapshot)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='large_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='% Large Cap equity (SEBI: Nifty 50 + Next 50) — latest MarketCapAllocation', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='mid_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='% Mid Cap equity (SEBI: Nifty Midcap 150) — latest MarketCapAllocation', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='small_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='% Small Cap equity (SEBI: residual) — latest MarketCapAllocation', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='fundscreenersnapshot',
            name='top_sector',
            field=models.CharField(blank=True, help_text='Top sector by weight from latest SectorAllocation', max_length=80),
        ),
    ]
