# Generated by Django 5.2.14 on 2026-05-27 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('as_of_month', models.DateField(help_text='YYYY-MM-01 — month of portfolio snapshot')),
                ('security_name', models.CharField(max_length=300)),
                ('isin', models.CharField(blank=True, max_length=15)),
                ('ticker', models.CharField(blank=True, max_length=20)),
                ('weight_pct', models.DecimalField(decimal_places=4, help_text='Weight in portfolio (%)', max_digits=7)),
                ('market_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='IN', max_length=50)),
                ('forward_pe', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('holding_type', models.CharField(default='equity', help_text='equity / debt / cash / other', max_length=20)),
                ('source', models.CharField(default='mstarpy', max_length=20)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='funds.scheme')),
            ],
            options={
                'ordering': ['-weight_pct'],
                'indexes': [models.Index(fields=['scheme', 'as_of_month'], name='holdings_ho_scheme__e9bcd5_idx'), models.Index(fields=['security_name'], name='holdings_ho_securit_dcde40_idx')],
                'unique_together': {('scheme', 'as_of_month', 'security_name')},
            },
        ),
        migrations.CreateModel(
            name='MarketCapAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('as_of_month', models.DateField()),
                ('large_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('mid_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('small_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('other_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('source', models.CharField(default='mstarpy', max_length=20)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcap_allocations', to='funds.scheme')),
            ],
            options={
                'unique_together': {('scheme', 'as_of_month')},
            },
        ),
        migrations.CreateModel(
            name='SectorAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('as_of_month', models.DateField()),
                ('sector', models.CharField(max_length=100)),
                ('weight_pct', models.DecimalField(decimal_places=4, max_digits=7)),
                ('source', models.CharField(default='mstarpy', max_length=20)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_allocations', to='funds.scheme')),
            ],
            options={
                'ordering': ['-weight_pct'],
                'unique_together': {('scheme', 'as_of_month', 'sector')},
            },
        ),
    ]
