# Generated by Django 5.2.14 on 2026-08-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketcapallocation',
            name='cap_method',
            field=models.CharField(default='unknown', help_text='caplist | mstarpy | yahoo | unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='marketcapallocation',
            name='cash_pct',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='% of portfolio in cash & equivalents', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='marketcapallocation',
            name='debt_pct',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='% of portfolio in debt instruments', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='marketcapallocation',
            name='equity_pct',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='% of portfolio in equities', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='marketcapallocation',
            name='other_pct',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Non-equity residual not classified as L/M/S', max_digits=7, null=True),
        ),
    ]
