# Generated by Django 5.2.14 on 2026-05-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataProvenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_label', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('object_id', models.BigIntegerField()),
                ('field_name', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=50)),
                ('fetched_at', models.DateTimeField()),
                ('is_stale', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['app_label', 'model_name', 'object_id'], name='core_datapr_app_lab_4915f7_idx')],
            },
        ),
    ]
