# Generated by Django 5.2.14 on 2026-07-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnBlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('markdown_path', models.CharField(max_length=500, unique=True)),
                ('thumbnail_path', models.CharField(blank=True, max_length=500)),
                ('read_time', models.CharField(blank=True, max_length=32)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('is_published', models.BooleanField(default=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
                'indexes': [models.Index(fields=['is_published', 'sort_order'], name='core_learnb_is_publ_ec8a58_idx')],
            },
        ),
        migrations.CreateModel(
            name='LearnPDFGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('pdf_path', models.CharField(max_length=500, unique=True)),
                ('cover_image_path', models.CharField(blank=True, max_length=500)),
                ('accent', models.CharField(blank=True, max_length=24)),
                ('size_kb', models.PositiveIntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('is_published', models.BooleanField(default=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
                'indexes': [models.Index(fields=['is_published', 'sort_order'], name='core_learnp_is_publ_a36ded_idx')],
            },
        ),
    ]
