# Generated by Django 5.2.14 on 2026-07-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_learnblogpost_learnpdfguide'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='learnpdfguide',
            name='core_learnp_is_publ_a36ded_idx',
        ),
        migrations.AddField(
            model_name='learnblogpost',
            name='tags',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='learnpdfguide',
            name='category',
            field=models.CharField(choices=[('chapters', 'Chapterwise Guides'), ('handbook', 'Complete Handbook'), ('other', 'Other Guides')], default='other', max_length=24),
        ),
        migrations.AddField(
            model_name='learnpdfguide',
            name='tags',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='learnpdfguide',
            index=models.Index(fields=['is_published', 'sort_order', 'category'], name='core_learnp_is_publ_fd493a_idx'),
        ),
    ]
