# Generated by Django 5.2.14 on 2026-07-14 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_learnpdfguide_core_learnp_is_publ_a36ded_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnpdfguide',
            name='downloadable',
            field=models.BooleanField(default=False, help_text='Allow users to download this PDF'),
        ),
    ]
