# Generated by Django 5.2.14 on 2026-07-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_downloadable_to_learnpdfguide'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnblogpost',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
