# Generated by Django 5.2.14 on 2026-05-27 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('risk_level', models.CharField(choices=[('conservative', 'Conservative'), ('moderate', 'Moderate'), ('aggressive', 'Aggressive')], default='moderate', max_length=20)),
                ('horizon', models.CharField(choices=[('1y', '< 1 Year'), ('1_3y', '1-3 Years'), ('3_5y', '3-5 Years'), ('5_10y', '5-10 Years'), ('10y_plus', '10+ Years')], default='3_5y', max_length=20)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rec_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FundRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, default=0, help_text='Composite score (higher = better fit)', max_digits=6)),
                ('rank', models.IntegerField(default=0)),
                ('reason', models.TextField(blank=True, help_text='Human-readable explanation')),
                ('category', models.CharField(blank=True, help_text='SEBI category for grouping', max_length=200)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.scheme')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='recommendations.recommendationprofile')),
            ],
            options={
                'ordering': ['category', 'rank'],
            },
        ),
    ]
