# Generated by Django 5.2.14 on 2026-05-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundrecommendation',
            options={'ordering': ['role', 'rank']},
        ),
        migrations.RemoveField(
            model_name='recommendationprofile',
            name='horizon',
        ),
        migrations.RemoveField(
            model_name='recommendationprofile',
            name='risk_level',
        ),
        migrations.AddField(
            model_name='fundrecommendation',
            name='role',
            field=models.CharField(choices=[('core', 'Core'), ('satellite', 'Satellite')], default='core', max_length=20),
        ),
        migrations.AddField(
            model_name='recommendationprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendationprofile',
            name='core_debt_pct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recommendationprofile',
            name='core_equity_pct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recommendationprofile',
            name='debt_load',
            field=models.CharField(choices=[('none', 'No Debt'), ('low', 'Low (e.g. standard EMI)'), ('moderate', 'Moderate'), ('high', 'High Burden')], default='low', max_length=20),
        ),
        migrations.AddField(
            model_name='recommendationprofile',
            name='dependents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recommendationprofile',
            name='emergency_fund_months',
            field=models.IntegerField(default=3, help_text='Months of expenses saved'),
        ),
        migrations.AddField(
            model_name='recommendationprofile',
            name='final_risk_profile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recommendationprofile',
            name='goal_horizon',
            field=models.CharField(choices=[('1y', '< 1 Year'), ('1_3y', '1-3 Years'), ('3_5y', '3-5 Years'), ('5_10y', '5-10 Years'), ('10y_plus', '10+ Years')], default='5_10y', max_length=20),
        ),
        migrations.AddField(
            model_name='recommendationprofile',
            name='goal_type',
            field=models.CharField(choices=[('emergency', 'Emergency Fund'), ('house', 'Buying a House'), ('education', 'Child Education'), ('retirement', 'Retirement'), ('wealth', 'Wealth Creation'), ('tax_saving', 'Tax Saving'), ('income', 'Regular Income')], default='wealth', max_length=20),
        ),
        migrations.AddField(
            model_name='recommendationprofile',
            name='hands_on',
            field=models.CharField(choices=[('simple', 'Keep it Simple'), ('active', 'Active/Thematic is fine')], default='simple', max_length=20),
        ),
        migrations.AddField(
            model_name='recommendationprofile',
            name='income_stability',
            field=models.CharField(choices=[('stable', 'Stable Salary'), ('variable', 'Variable/Business'), ('irregular', 'Irregular/Freelance')], default='stable', max_length=20),
        ),
        migrations.AddField(
            model_name='recommendationprofile',
            name='income_type',
            field=models.CharField(choices=[('salary', 'Monthly Salary'), ('variable', 'Variable Income'), ('lumpsum', 'Lump Sum Capital')], default='salary', max_length=20),
        ),
        migrations.AddField(
            model_name='recommendationprofile',
            name='investing_experience',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='intermediate', max_length=20),
        ),
        migrations.AddField(
            model_name='recommendationprofile',
            name='investor_archetype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recommendationprofile',
            name='liquidity_need',
            field=models.CharField(choices=[('low', 'Low (Locked in is fine)'), ('medium', 'Medium'), ('high', 'High (Might need anytime)')], default='low', max_length=20),
        ),
        migrations.AddField(
            model_name='recommendationprofile',
            name='loss_reaction',
            field=models.CharField(choices=[('sell', 'Panic and Sell'), ('concerned', 'Concerned but Hold'), ('calm', 'Stay Calm'), ('buy_more', 'Buy More at Discount')], default='calm', max_length=20),
        ),
        migrations.AddField(
            model_name='recommendationprofile',
            name='option_style',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recommendationprofile',
            name='payout_preference',
            field=models.CharField(choices=[('growth', 'Growth (Compounding)'), ('idcw', 'IDCW (Periodic Payouts)')], default='growth', max_length=20),
        ),
        migrations.AddField(
            model_name='recommendationprofile',
            name='plan_style',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recommendationprofile',
            name='rebalance_frequency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recommendationprofile',
            name='recommended_strategy',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recommendationprofile',
            name='risk_capacity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recommendationprofile',
            name='risk_tolerance',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recommendationprofile',
            name='satellite_pct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recommendationprofile',
            name='tax_sensitivity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High (Tax efficiency critical)')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='fundrecommendation',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Composite score (3Y CAGR + Sharpe + ER)', max_digits=6),
        ),
    ]
