"""
management/commands/push_to_kaggle.py
======================================
Exports database tables to CSV and pushes/updates a Kaggle dataset.

Usage:
    # First time -- creates the dataset on Kaggle
    python manage.py push_to_kaggle --create

    # Subsequent updates -- publishes a new version
    python manage.py push_to_kaggle

    # With custom version notes
    python manage.py push_to_kaggle --message "Monthly refresh -- Aug 2026"

    # Skip large NAV history (fast metadata-only update)
    python manage.py push_to_kaggle --skip-nav

    # Dry run -- exports CSVs only, does not push to Kaggle
    python manage.py push_to_kaggle --dry-run

Requirements:
    pip install kaggle   (already in requirements.txt)

Credentials:
    Set environment variables (or ~/.kaggle/kaggle.json):
        KAGGLE_USERNAME = your-username
        KAGGLE_KEY      = your-api-key

    Get your API key: https://www.kaggle.com/settings -> API -> Create New Token
"""

import csv
import json
import logging
import os
import shutil
import subprocess
import sys
import tempfile
from datetime import date
from pathlib import Path

from django.core.management.base import BaseCommand, CommandError
from django.db import connection

logger = logging.getLogger('mfanalysis')


# ============================================================================
# Dataset metadata
# (Kaggle dataset title must be between 6 and 50 characters)
# ============================================================================

DATASET_TITLE    = "Indian Mutual Funds: NAV & Analytics Dataset"
DATASET_SUBTITLE = (
    "Daily NAV history for 2,000+ SEBI-registered Indian mutual funds "
    "(Direct Growth Open Funds + ETFs) with trailing returns, risk metrics, "
    "screener scores, and benchmark data."
)
DATASET_LICENSES = [{"name": "CC0-1.0"}]


# ============================================================================
# README template
# ============================================================================

def _generate_readme() -> str:
    """Generate README Markdown with dynamic last-updated timestamp and project links."""
    as_of = date.today().strftime('%d %B %Y')
    return f"""\
# Indian Mutual Funds: NAV & Analytics Dataset

A comprehensive, curated dataset of SEBI-registered Indian mutual funds covering
daily NAV history, pre-computed screener scores, risk-adjusted performance metrics,
and benchmark index data.

**Last Updated:** {as_of}

---

## Live Application & Open Source Project

This dataset is actively maintained and generated by the open-source
**MutualFundAnalysis** research engine:

- **Live Web Application:** [Mutual Fund Research Dashboard](https://mfanalysis-web-picv.onrender.com/)
  - Interactive screener, rolling return & volatility charts, portfolio analyzer,
    and live market strip.
- **GitHub Repository:** [amansingh2116/MutualFundAnalysis](https://github.com/amansingh2116/MutualFundAnalysis)
  - Full codebase: automated data pipelines, risk analytics, backtesting engine,
    and Django architecture.

---

## Dataset Contents

| File | Description |
|------|-------------|
| `funds.csv` | Master registry of active schemes (AMC, Category, AUM, TER, ISIN) |
| `fund_screener.csv` | Pre-computed trailing returns (1M-10Y), risk metrics, and rolling stats |
| `fund_scores.csv` | 6-pillar 100-point quantitative score breakdown and badges |
| `nav_history.csv` | Daily historical NAV for every scheme since inception |
| `benchmarks.csv` | Daily index closing values (Nifty 50, Midcap 150, Smallcap 250, etc.) |
| `benchmark_returns.csv` | Benchmark trailing return snapshots and volatility |
| `trailing_returns.csv` | Fund-level annualized trailing CAGR returns vs benchmark by period |
| `risk_metrics.csv` | Volatility, Sharpe, Sortino, Alpha, Beta, Max Drawdown, Info Ratio |

---

## Data Sources & Verification

- **AMFI** (Association of Mutual Funds in India): Daily scheme master & NAV
- **mfapi.in**: Historical NAV time series back to inception
- **NSE / Benchmark Providers**: Tri-party benchmark indices

---

## Methodology & Universe Filters

1. **Universe**: Open-Ended Direct Growth schemes + ETFs only
   (eliminates Regular plan commission drag and dividend distortions)
2. **Analytics**: Trailing returns, std deviation, Sharpe (RBI 91-day T-Bill risk-free rate),
   Sortino downside ratio, Jensen's Alpha vs category benchmarks
3. **Scoring**: Multi-factor composite blending returns, downside protection, and consistency

---

## Quick Start in Python

```python
import pandas as pd

# Load fund master registry
funds = pd.read_csv('funds.csv')
print(f"Total funds: {{len(funds)}}")

# Top funds by 3Y CAGR
screener = pd.read_csv('fund_screener.csv')
top = screener.sort_values('cagr_3y_pct', ascending=False)[
    ['scheme_name', 'fund_house', 'scheme_category', 'cagr_3y_pct', 'sharpe_ratio']
].head(10)
print(top)

# Historical NAV for a specific fund
nav = pd.read_csv('nav_history.csv', parse_dates=['date'])
fund_nav = nav[nav['amfi_code'] == 119598].sort_values('date')
```

---

## License & Attribution

Data sourced from public AMFI records. Published under **CC0: Public Domain Dedication**.
If you use this dataset, a mention of the
[GitHub repository](https://github.com/amansingh2116/MutualFundAnalysis) is appreciated!
"""


# ============================================================================
# Helpers
# ============================================================================

def _kaggle_username() -> str:
    """Return Kaggle username from env or ~/.kaggle/kaggle.json."""
    username = os.environ.get('KAGGLE_USERNAME', '')
    if not username:
        cfg = Path.home() / '.kaggle' / 'kaggle.json'
        if cfg.exists():
            with open(cfg) as f:
                username = json.load(f).get('username', '')
    return username


def _run_kaggle(args: list[str], cwd: str) -> str:
    """Run a kaggle CLI command, raising CommandError on failure."""
    cmd = [sys.executable, '-m', 'kaggle'] + args
    result = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    if result.returncode != 0:
        raise CommandError(
            f"kaggle command failed:\n{result.stdout}\n{result.stderr}"
        )
    return result.stdout


def _export_table_to_csv(sql: str, filepath: str, stdout) -> int:
    """Execute SQL and write results to CSV. Returns row count."""
    with connection.cursor() as cur:
        cur.execute(sql)
        columns = [col[0] for col in cur.description]
        with open(filepath, 'w', newline='', encoding='utf-8') as f:
            writer = csv.writer(f)
            writer.writerow(columns)
            rows = 0
            while True:
                batch = cur.fetchmany(10_000)
                if not batch:
                    break
                writer.writerows(batch)
                rows += len(batch)
                if rows % 100_000 == 0:
                    stdout.write(f"\r    {rows:,} rows...", ending='')
                    stdout.flush()
    return rows


# ============================================================================
# SQL queries for each exported table (verified against DB schema)
# ============================================================================

EXPORT_QUERIES = {

    'funds.csv': """
        SELECT
            s.amfi_code,
            s.isin_growth,
            s.isin_idcw,
            s.scheme_name,
            s.fund_house,
            s.scheme_type,
            s.scheme_category,
            s.plan,
            s.is_direct,
            s.is_etf,
            s.is_active,
            s.expense_ratio,
            s.aum_cr,
            s.nav_latest,
            s.nav_date,
            s.morningstar_id,
            s.yahoo_ticker
        FROM funds_scheme s
        WHERE s.is_active = true
        ORDER BY s.amfi_code
    """,

    'fund_screener.csv': """
        SELECT
            s.amfi_code,
            s.scheme_name,
            s.fund_house,
            s.scheme_category,
            s.is_etf,
            snap.expense_ratio,
            snap.aum_cr,
            snap.returns_1m_pct,
            snap.returns_3m_pct,
            snap.returns_6m_pct,
            snap.returns_1y_pct,
            snap.returns_3y_pct,
            snap.returns_5y_pct,
            snap.cagr_3y_pct,
            snap.cagr_7y_pct,
            snap.cagr_10y_pct,
            snap.cagr_si_pct,
            snap.rolling_return_3y_pct,
            snap.rolling_return_5y_pct,
            snap.volatility_1y_pct,
            snap.volatility_3y_pct,
            snap.volatility_5y_pct,
            snap.sharpe_ratio,
            snap.sortino_ratio,
            snap.max_drawdown,
            snap.alpha_3y,
            snap.beta_3y,
            snap.info_ratio_3y,
            snap.updated_at
        FROM funds_fundscreenersnapshot snap
        JOIN funds_scheme s ON s.id = snap.scheme_id
        ORDER BY s.amfi_code
    """,

    'fund_scores.csv': """
        SELECT
            s.amfi_code,
            ms.score_version,
            ms.final_score,
            ms.confidence,
            ms.score_badge,
            ms.score_performance,
            ms.score_risk,
            ms.score_cost,
            ms.score_composition,
            ms.score_debt,
            ms.score_manager,
            ms.updated_at
        FROM funds_fundmodelscore ms
        JOIN funds_scheme s ON s.id = ms.scheme_id
        ORDER BY s.amfi_code
    """,

    'nav_history.csv': """
        SELECT
            s.amfi_code,
            n.date,
            n.nav
        FROM funds_navhistory n
        JOIN funds_scheme s ON s.id = n.scheme_id
        ORDER BY s.amfi_code, n.date
    """,

    'benchmarks.csv': """
        SELECT
            bi.name AS benchmark_name,
            bi.yahoo_ticker,
            bn.date,
            bn.close,
            bn.source
        FROM benchmarks_benchmarkindex bi
        JOIN benchmarks_benchmarknav bn ON bn.index_id = bi.id
        ORDER BY bi.name, bn.date
    """,

    'benchmark_returns.csv': """
        SELECT
            bi.name AS benchmark_name,
            br.ret_1w,
            br.ret_1m,
            br.ret_3m,
            br.ret_6m,
            br.ret_ytd,
            br.ret_1y,
            br.ret_3y,
            br.ret_5y,
            br.ret_10y,
            br.ret_since_launch,
            br.volatility_1y,
            br.volatility_3y,
            br.volatility_5y,
            br.updated_at
        FROM benchmarks_benchmarkindex bi
        JOIN benchmarks_benchmarkreturns br ON br.index_id = bi.id
        ORDER BY bi.name
    """,

    'trailing_returns.csv': """
        SELECT
            s.amfi_code,
            tr.period,
            tr.years,
            tr.cagr_pct,
            tr.bm_cagr,
            tr.excess,
            tr.as_of
        FROM analytics_trailingreturn tr
        JOIN funds_scheme s ON s.id = tr.scheme_id
        ORDER BY s.amfi_code, tr.years
    """,

    'risk_metrics.csv': """
        SELECT
            s.amfi_code,
            rm.period,
            rm.period_days,
            rm.std_dev_ann AS volatility,
            rm.sharpe_ratio,
            rm.sortino_ratio,
            rm.max_drawdown,
            rm.beta,
            rm.alpha_ann AS alpha,
            rm.r_squared,
            rm.info_ratio,
            rm.as_of
        FROM analytics_riskmetrics rm
        JOIN funds_scheme s ON s.id = rm.scheme_id
        ORDER BY s.amfi_code, rm.period
    """,
}


# ============================================================================
# Management command
# ============================================================================

class Command(BaseCommand):
    help = 'Export database to CSV and push to Kaggle as a dataset'

    def add_arguments(self, parser):
        parser.add_argument(
            '--create',
            action='store_true',
            help='Create a brand-new dataset (first time only). Omit for subsequent version updates.',
        )
        parser.add_argument(
            '--message', '-m',
            default=f"Data refresh -- {date.today().strftime('%B %Y')}",
            help='Version message for this Kaggle update.',
        )
        parser.add_argument(
            '--skip-nav',
            action='store_true',
            help='Skip exporting nav_history.csv (large file, ~600 MB). Use for fast metadata-only updates.',
        )
        parser.add_argument(
            '--output-dir',
            default=None,
            help='Directory to write CSV exports (default: system temp dir, cleaned up after push).',
        )
        parser.add_argument(
            '--dry-run',
            action='store_true',
            help='Export CSVs only -- do not push to Kaggle.',
        )
        parser.add_argument(
            '--slug',
            default='indian-mutual-funds-complete-nav-analytics',
            help='Kaggle dataset slug (used in the dataset URL).',
        )

    def handle(self, *args, **options):
        create   = options['create']
        message  = options['message']
        skip_nav = options['skip_nav']
        dry_run  = options['dry_run']
        slug     = options['slug']

        username = _kaggle_username()
        if not username and not dry_run:
            raise CommandError(
                "Kaggle username not found. Set KAGGLE_USERNAME env var or "
                "create ~/.kaggle/kaggle.json via: kaggle datasets list"
            )

        # Resolve export directory
        use_temp = options['output_dir'] is None
        export_dir = Path(options['output_dir']) if options['output_dir'] else Path(tempfile.mkdtemp())
        export_dir.mkdir(parents=True, exist_ok=True)

        self.stdout.write(self.style.MIGRATE_HEADING(
            f"\nMutualFundAnalysis -- Kaggle Dataset Export"
            f"\n  Target:    {username}/{slug}"
            f"\n  Export to: {export_dir}"
            f"\n  Mode:      {'CREATE new dataset' if create else 'UPDATE existing version'}"
            f"\n  Dry run:   {dry_run}\n"
        ))

        try:
            # ── Export CSVs ────────────────────────────────────────────────
            total_rows = 0
            queries = dict(EXPORT_QUERIES)

            if skip_nav:
                queries.pop('nav_history.csv', None)
                self.stdout.write("  [skip] nav_history.csv (--skip-nav flag set)")

            for filename, sql in queries.items():
                filepath = str(export_dir / filename)
                self.stdout.write(f"  Exporting {filename}...", ending='')
                self.stdout.flush()
                try:
                    rows = _export_table_to_csv(sql, filepath, self.stdout)
                    total_rows += rows
                    size_mb = os.path.getsize(filepath) / (1024 * 1024)
                    self.stdout.write(f"\r  [OK] {filename:<30} {rows:>10,} rows  ({size_mb:.1f} MB)")
                except Exception as e:
                    self.stdout.write(self.style.WARNING(f"\r  [WARN] {filename} -- skipped: {e}"))

            # ── Write README.md ────────────────────────────────────────────
            readme_content = _generate_readme()
            readme_path = export_dir / 'README.md'
            readme_path.write_text(readme_content, encoding='utf-8')
            self.stdout.write(f"\n  [OK] README.md written (Last Updated: {date.today().strftime('%d %B %Y')})")

            # ── Write dataset-metadata.json ────────────────────────────────
            meta = {
                "title":       DATASET_TITLE,
                "id":          f"{username}/{slug}",
                "licenses":    DATASET_LICENSES,
                "subtitle":    DATASET_SUBTITLE,
                "description": readme_content,
                "keywords": [
                    "mutual funds", "india", "finance", "investment",
                    "nifty", "nav", "amfi", "sebi", "etf"
                ],
                "collaborators": [],
                "data": [
                    {
                        "description": "",
                        "name": f,
                        "totalBytes": os.path.getsize(str(export_dir / f))
                    }
                    for f in sorted(os.listdir(str(export_dir)))
                    if f.endswith('.csv')
                ],
            }
            meta_path = export_dir / 'dataset-metadata.json'
            meta_path.write_text(json.dumps(meta, indent=2), encoding='utf-8')
            self.stdout.write(f"  [OK] dataset-metadata.json written")

            self.stdout.write(self.style.SUCCESS(
                f"\n  Export complete: {total_rows:,} total rows across {len(queries)} files"
            ))

            if dry_run:
                self.stdout.write(self.style.WARNING(
                    f"\nDRY RUN -- files saved to: {export_dir}\n"
                    f"Re-run without --dry-run to push to Kaggle."
                ))
                return

            # ── Push to Kaggle ─────────────────────────────────────────────
            self.stdout.write(f"\nPushing to Kaggle as {username}/{slug}...")

            if create:
                self.stdout.write("  Creating new dataset (first time)...")
                _run_kaggle(
                    ['datasets', 'create', '-p', str(export_dir), '--dir-mode', 'zip'],
                    cwd=str(export_dir)
                )
            else:
                self.stdout.write(f"  Publishing new version: '{message}'...")
                _run_kaggle(
                    ['datasets', 'version', '-p', str(export_dir),
                     '-m', message, '--dir-mode', 'zip'],
                    cwd=str(export_dir)
                )

            self.stdout.write(self.style.SUCCESS(
                f"\nDataset published: https://www.kaggle.com/datasets/{username}/{slug}\n"
            ))

        finally:
            if use_temp and not dry_run:
                shutil.rmtree(str(export_dir), ignore_errors=True)
