# Generated by Django 5.2.14 on 2026-05-27 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('benchmarks', '0001_initial'),
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('return_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('bm_return', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('outperformed', models.BooleanField(blank=True, null=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_returns', to='funds.scheme')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('scheme', 'year')},
            },
        ),
        migrations.CreateModel(
            name='RiskMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(choices=[('3Y', '3 Years'), ('5Y', '5 Years')], max_length=5)),
                ('period_days', models.IntegerField()),
                ('std_dev_ann', models.DecimalField(blank=True, decimal_places=4, help_text='Annualised std dev of daily returns (%)', max_digits=8, null=True)),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('sortino_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('max_drawdown', models.DecimalField(blank=True, decimal_places=4, help_text='Maximum peak-to-trough decline (%)', max_digits=8, null=True)),
                ('beta', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('alpha_ann', models.DecimalField(blank=True, decimal_places=4, help_text="Annualised Jensen's alpha (%)", max_digits=8, null=True)),
                ('r_squared', models.DecimalField(blank=True, decimal_places=4, help_text='R² vs benchmark (%)', max_digits=8, null=True)),
                ('upside_capture', models.DecimalField(blank=True, decimal_places=4, help_text='Upside capture ratio (%)', max_digits=8, null=True)),
                ('downside_capture', models.DecimalField(blank=True, decimal_places=4, help_text='Downside capture ratio (%)', max_digits=8, null=True)),
                ('tracking_error', models.DecimalField(blank=True, decimal_places=4, help_text='Annualised tracking error (%)', max_digits=8, null=True)),
                ('info_ratio', models.DecimalField(blank=True, decimal_places=4, help_text='Information ratio', max_digits=8, null=True)),
                ('rf_rate_used', models.DecimalField(decimal_places=3, default=0.065, help_text='Risk-free rate used (e.g. 0.065 = 6.5%)', max_digits=5)),
                ('as_of', models.DateField()),
                ('ms_std_dev_3y', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('ms_sharpe_3y', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('ms_beta_3y', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('ms_alpha_3y', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('benchmark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='benchmarks.benchmarkindex')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_metrics', to='funds.scheme')),
            ],
            options={
                'indexes': [models.Index(fields=['scheme', 'period', 'as_of'], name='analytics_r_scheme__777da2_idx')],
                'unique_together': {('scheme', 'period', 'as_of')},
            },
        ),
        migrations.CreateModel(
            name='RollingReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('window', models.CharField(choices=[('1Y', '1 Year'), ('3Y', '3 Years'), ('5Y', '5 Years')], max_length=5)),
                ('window_days', models.IntegerField(help_text='252 for 1Y, 756 for 3Y, 1260 for 5Y')),
                ('min_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('max_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('mean_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('std_dev', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('win_rate_0', models.DecimalField(blank=True, decimal_places=2, help_text='% of rolling periods with return > 0%', max_digits=5, null=True)),
                ('win_rate_12', models.DecimalField(blank=True, decimal_places=2, help_text='% of rolling periods with return > 12%', max_digits=5, null=True)),
                ('as_of', models.DateField()),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolling_returns', to='funds.scheme')),
            ],
            options={
                'ordering': ['window'],
                'unique_together': {('scheme', 'window', 'as_of')},
            },
        ),
        migrations.CreateModel(
            name='TrailingReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(choices=[('1M', '1 Month'), ('3M', '3 Months'), ('6M', '6 Months'), ('1Y', '1 Year'), ('2Y', '2 Years'), ('3Y', '3 Years'), ('5Y', '5 Years'), ('7Y', '7 Years'), ('10Y', '10 Years'), ('SI', 'Since Inception')], max_length=5)),
                ('years', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cagr_pct', models.DecimalField(blank=True, decimal_places=4, help_text='Fund CAGR in %', max_digits=8, null=True)),
                ('bm_cagr', models.DecimalField(blank=True, decimal_places=4, help_text='Benchmark CAGR for same period in %', max_digits=8, null=True)),
                ('excess', models.DecimalField(blank=True, decimal_places=4, help_text='fund_cagr - bm_cagr (alpha proxy)', max_digits=8, null=True)),
                ('as_of', models.DateField(help_text='Date of last NAV used for computation')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trailing_returns', to='funds.scheme')),
            ],
            options={
                'ordering': ['years'],
                'indexes': [models.Index(fields=['scheme', 'as_of'], name='analytics_t_scheme__51e683_idx')],
                'unique_together': {('scheme', 'period', 'as_of')},
            },
        ),
    ]
