# Generated by Django 5.2.14 on 2026-07-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollingreturn',
            name='median_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='riskmetrics',
            name='period',
            field=models.CharField(choices=[('1Y', '1 Year'), ('3Y', '3 Years'), ('5Y', '5 Years'), ('7Y', '7 Years'), ('SI', 'Since Inception')], max_length=5),
        ),
        migrations.AlterField(
            model_name='rollingreturn',
            name='window',
            field=models.CharField(choices=[('1Y', '1 Year'), ('3Y', '3 Years'), ('5Y', '5 Years'), ('7Y', '7 Years')], max_length=5),
        ),
    ]
