# Generated by Django 5.2.14 on 2026-08-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_rollingreturn_median_pct_alter_riskmetrics_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarreturn',
            name='bm_return',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='calendarreturn',
            name='return_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='riskmetrics',
            name='alpha_ann',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Annualised Jensen's alpha (%)", max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='riskmetrics',
            name='beta',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='riskmetrics',
            name='downside_capture',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Downside capture ratio (%)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='riskmetrics',
            name='info_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Information ratio', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='riskmetrics',
            name='max_drawdown',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Maximum peak-to-trough decline (%)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='riskmetrics',
            name='ms_alpha_3y',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='riskmetrics',
            name='ms_beta_3y',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='riskmetrics',
            name='ms_sharpe_3y',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='riskmetrics',
            name='ms_std_dev_3y',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='riskmetrics',
            name='r_squared',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='R² vs benchmark (%)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='riskmetrics',
            name='sharpe_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='riskmetrics',
            name='sortino_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='riskmetrics',
            name='std_dev_ann',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Annualised std dev of daily returns (%)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='riskmetrics',
            name='tracking_error',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Annualised tracking error (%)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='riskmetrics',
            name='upside_capture',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Upside capture ratio (%)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='rollingreturn',
            name='max_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='rollingreturn',
            name='mean_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='rollingreturn',
            name='median_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='rollingreturn',
            name='min_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='rollingreturn',
            name='std_dev',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='trailingreturn',
            name='bm_cagr',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Benchmark CAGR for same period in %', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='trailingreturn',
            name='cagr_pct',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Fund CAGR in %', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='trailingreturn',
            name='excess',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='fund_cagr - bm_cagr (alpha proxy)', max_digits=12, null=True),
        ),
    ]
