# Generated by Django 5.2.14 on 2026-05-27 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='My Portfolio', max_length=100)),
                ('is_private', models.BooleanField(default=True, help_text='Always True for CAS data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheme_name', models.CharField(help_text='Raw name from CAS PDF before matching', max_length=300)),
                ('amfi_code', models.CharField(blank=True, max_length=10)),
                ('tx_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('SIP', 'SIP'), ('REDEEM', 'Redeem'), ('SWITCH_IN', 'Switch In'), ('SWITCH_OUT', 'Switch Out'), ('DIV_PAYOUT', 'Dividend Payout'), ('DIV_REINV', 'Dividend Reinvestment')], max_length=15)),
                ('tx_date', models.DateField()),
                ('units', models.DecimalField(decimal_places=4, max_digits=15)),
                ('nav', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('folio', models.CharField(blank=True, max_length=30)),
                ('stamp_duty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolio.portfolio')),
                ('scheme', models.ForeignKey(blank=True, help_text='Linked after fuzzy matching CAS name to DB', null=True, on_delete=django.db.models.deletion.SET_NULL, to='funds.scheme')),
            ],
            options={
                'ordering': ['-tx_date'],
                'indexes': [models.Index(fields=['portfolio', 'tx_date'], name='portfolio_t_portfol_d2d2fb_idx'), models.Index(fields=['scheme', 'tx_date'], name='portfolio_t_scheme__2af1a5_idx')],
            },
        ),
    ]
