# Generated by Django 5.2.14 on 2026-07-06 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('plan_json', models.JSONField(help_text='Serialised PortfolioPlanV2 payload (assets + settings + rebalance)')),
                ('last_result_json', models.JSONField(blank=True, help_text='Cached result from last backtest run (optional, used for compare page)', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_strategies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Strategy',
                'verbose_name_plural': 'Saved Strategies',
                'ordering': ['-updated_at'],
            },
        ),
    ]
